# Generated by Django 5.1 on 2024-08-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='homeModel',
        ),
    ]
